---
- name: Manage Nexus repositories on "{{ target }}" group
  hosts: "{{ target }}"
  become: yes
  vars:
    nexus_username: "{{ lookup('env', 'NEXUS_USERNAME') }}"
    nexus_password: "{{ lookup('env', 'NEXUS_PASSWORD') }}"
  tasks:
    - name: Copy nexus.repo to /etc/yum.repos.d/
      ansible.builtin.template:
        src: "{{ src_path }}/nexus.repo"
        dest: /etc/yum.repos.d/nexus.repo

    - name: Update the yum cache "{{ target }}" group
      ansible.builtin.command:
        cmd: yum makecache
    
    - name: Add Amazon Corretto repository
      yum_repository:
        name: amazon-corretto
        description: Amazon Corretto repository
        baseurl: https://corretto.aws/downloads/resources/repos/amazon-corretto.repo
        gpgcheck: yes
        enabled: yes

    - name: Install Java on the "{{ target }}" group
      yum:
        name: java-11-amazon-corretto
        state: present
        disable_gpg_check: yes
      when: "'java_dev' in group_names or 'pipe_dev' in group_names"
      become: yes

    - name: Verify Java installation on "{{ target }}" group
      command: java -version
      when: "'java_dev' in group_names or 'pipe_dev' in group_names"
      become: yes
