---
- name: Execute rpm-test-default command on "{{ target }}" group
  hosts: "{{ target }}"
  become: yes
  tasks:
    - name: Run the test-app command
      command: systemctl status rpm-test-default
      register: result

    - name: Print the command output
      debug:
        msg: "{{ result.stdout }}"
